import { BORDER_CHAR, EMPTY_CHAR } from "./config";
import { textBox } from "./text-box";

describe("textBox", () => {
  it("works", () => {
    const { instructions, nextRow } = textBox({
      startRow: 0,
      columns: 20,
      margin: 1,
      padding: 1,
      text: "This is some sample text",
    });

    expect(nextRow).toBe(8);

    expect(instructions).toEqual([
      { row: 0, column: 0, character: EMPTY_CHAR },
      { row: 0, column: 1, character: EMPTY_CHAR },
      { row: 0, column: 2, character: EMPTY_CHAR },
      { row: 0, column: 3, character: EMPTY_CHAR },
      { row: 0, column: 4, character: EMPTY_CHAR },
      { row: 0, column: 5, character: EMPTY_CHAR },
      { row: 0, column: 6, character: EMPTY_CHAR },
      { row: 0, column: 7, character: EMPTY_CHAR },
      { row: 0, column: 8, character: EMPTY_CHAR },
      { row: 0, column: 9, character: EMPTY_CHAR },
      { row: 0, column: 10, character: EMPTY_CHAR },
      { row: 0, column: 11, character: EMPTY_CHAR },
      { row: 0, column: 12, character: EMPTY_CHAR },
      { row: 0, column: 13, character: EMPTY_CHAR },
      { row: 0, column: 14, character: EMPTY_CHAR },
      { row: 0, column: 15, character: EMPTY_CHAR },
      { row: 0, column: 16, character: EMPTY_CHAR },
      { row: 0, column: 17, character: EMPTY_CHAR },
      { row: 0, column: 18, character: EMPTY_CHAR },
      { row: 0, column: 19, character: EMPTY_CHAR },
      //
      { row: 1, column: 0, character: EMPTY_CHAR },
      { row: 1, column: 1, character: BORDER_CHAR },
      { row: 1, column: 2, character: BORDER_CHAR },
      { row: 1, column: 3, character: BORDER_CHAR },
      { row: 1, column: 4, character: BORDER_CHAR },
      { row: 1, column: 5, character: BORDER_CHAR },
      { row: 1, column: 6, character: BORDER_CHAR },
      { row: 1, column: 7, character: BORDER_CHAR },
      { row: 1, column: 8, character: BORDER_CHAR },
      { row: 1, column: 9, character: BORDER_CHAR },
      { row: 1, column: 10, character: BORDER_CHAR },
      { row: 1, column: 11, character: BORDER_CHAR },
      { row: 1, column: 12, character: BORDER_CHAR },
      { row: 1, column: 13, character: BORDER_CHAR },
      { row: 1, column: 14, character: BORDER_CHAR },
      { row: 1, column: 15, character: BORDER_CHAR },
      { row: 1, column: 16, character: BORDER_CHAR },
      { row: 1, column: 17, character: BORDER_CHAR },
      { row: 1, column: 18, character: BORDER_CHAR },
      { row: 1, column: 19, character: EMPTY_CHAR },
      //
      { row: 2, column: 0, character: EMPTY_CHAR },
      { row: 2, column: 1, character: BORDER_CHAR },
      { row: 2, column: 2, character: EMPTY_CHAR },
      { row: 2, column: 3, character: EMPTY_CHAR },
      { row: 2, column: 4, character: EMPTY_CHAR },
      { row: 2, column: 5, character: EMPTY_CHAR },
      { row: 2, column: 6, character: EMPTY_CHAR },
      { row: 2, column: 7, character: EMPTY_CHAR },
      { row: 2, column: 8, character: EMPTY_CHAR },
      { row: 2, column: 9, character: EMPTY_CHAR },
      { row: 2, column: 10, character: EMPTY_CHAR },
      { row: 2, column: 11, character: EMPTY_CHAR },
      { row: 2, column: 12, character: EMPTY_CHAR },
      { row: 2, column: 13, character: EMPTY_CHAR },
      { row: 2, column: 14, character: EMPTY_CHAR },
      { row: 2, column: 15, character: EMPTY_CHAR },
      { row: 2, column: 16, character: EMPTY_CHAR },
      { row: 2, column: 17, character: EMPTY_CHAR },
      { row: 2, column: 18, character: BORDER_CHAR },
      { row: 2, column: 19, character: EMPTY_CHAR },
      //
      { row: 3, column: 0, character: EMPTY_CHAR },
      { row: 3, column: 1, character: BORDER_CHAR },
      { row: 3, column: 2, character: EMPTY_CHAR },
      { row: 3, column: 3, character: "T" },
      { row: 3, column: 4, character: "h" },
      { row: 3, column: 5, character: "i" },
      { row: 3, column: 6, character: "s" },
      { row: 3, column: 7, character: " " },
      { row: 3, column: 8, character: "i" },
      { row: 3, column: 9, character: "s" },
      { row: 3, column: 10, character: " " },
      { row: 3, column: 11, character: "s" },
      { row: 3, column: 12, character: "o" },
      { row: 3, column: 13, character: "m" },
      { row: 3, column: 14, character: "e" },
      { row: 3, column: 15, character: " " },
      { row: 3, column: 16, character: "s" },
      { row: 3, column: 17, character: EMPTY_CHAR },
      { row: 3, column: 18, character: BORDER_CHAR },
      { row: 3, column: 19, character: EMPTY_CHAR },
      //
      { row: 4, column: 0, character: EMPTY_CHAR },
      { row: 4, column: 1, character: BORDER_CHAR },
      { row: 4, column: 2, character: EMPTY_CHAR },
      { row: 4, column: 3, character: "a" },
      { row: 4, column: 4, character: "m" },
      { row: 4, column: 5, character: "p" },
      { row: 4, column: 6, character: "l" },
      { row: 4, column: 7, character: "e" },
      { row: 4, column: 8, character: " " },
      { row: 4, column: 9, character: "t" },
      { row: 4, column: 10, character: "e" },
      { row: 4, column: 11, character: "x" },
      { row: 4, column: 12, character: "t" },
      { row: 4, column: 13, character: EMPTY_CHAR },
      { row: 4, column: 14, character: EMPTY_CHAR },
      { row: 4, column: 15, character: EMPTY_CHAR },
      { row: 4, column: 16, character: EMPTY_CHAR },
      { row: 4, column: 17, character: EMPTY_CHAR },
      { row: 4, column: 18, character: BORDER_CHAR },
      { row: 4, column: 19, character: EMPTY_CHAR },
      //
      { row: 5, column: 0, character: EMPTY_CHAR },
      { row: 5, column: 1, character: BORDER_CHAR },
      { row: 5, column: 2, character: EMPTY_CHAR },
      { row: 5, column: 3, character: EMPTY_CHAR },
      { row: 5, column: 4, character: EMPTY_CHAR },
      { row: 5, column: 5, character: EMPTY_CHAR },
      { row: 5, column: 6, character: EMPTY_CHAR },
      { row: 5, column: 7, character: EMPTY_CHAR },
      { row: 5, column: 8, character: EMPTY_CHAR },
      { row: 5, column: 9, character: EMPTY_CHAR },
      { row: 5, column: 10, character: EMPTY_CHAR },
      { row: 5, column: 11, character: EMPTY_CHAR },
      { row: 5, column: 12, character: EMPTY_CHAR },
      { row: 5, column: 13, character: EMPTY_CHAR },
      { row: 5, column: 14, character: EMPTY_CHAR },
      { row: 5, column: 15, character: EMPTY_CHAR },
      { row: 5, column: 16, character: EMPTY_CHAR },
      { row: 5, column: 17, character: EMPTY_CHAR },
      { row: 5, column: 18, character: BORDER_CHAR },
      { row: 5, column: 19, character: EMPTY_CHAR },
      //
      { row: 6, column: 0, character: EMPTY_CHAR },
      { row: 6, column: 1, character: BORDER_CHAR },
      { row: 6, column: 2, character: BORDER_CHAR },
      { row: 6, column: 3, character: BORDER_CHAR },
      { row: 6, column: 4, character: BORDER_CHAR },
      { row: 6, column: 5, character: BORDER_CHAR },
      { row: 6, column: 6, character: BORDER_CHAR },
      { row: 6, column: 7, character: BORDER_CHAR },
      { row: 6, column: 8, character: BORDER_CHAR },
      { row: 6, column: 9, character: BORDER_CHAR },
      { row: 6, column: 10, character: BORDER_CHAR },
      { row: 6, column: 11, character: BORDER_CHAR },
      { row: 6, column: 12, character: BORDER_CHAR },
      { row: 6, column: 13, character: BORDER_CHAR },
      { row: 6, column: 14, character: BORDER_CHAR },
      { row: 6, column: 15, character: BORDER_CHAR },
      { row: 6, column: 16, character: BORDER_CHAR },
      { row: 6, column: 17, character: BORDER_CHAR },
      { row: 6, column: 18, character: BORDER_CHAR },
      { row: 6, column: 19, character: EMPTY_CHAR },
      //
      { row: 7, column: 0, character: EMPTY_CHAR },
      { row: 7, column: 1, character: EMPTY_CHAR },
      { row: 7, column: 2, character: EMPTY_CHAR },
      { row: 7, column: 3, character: EMPTY_CHAR },
      { row: 7, column: 4, character: EMPTY_CHAR },
      { row: 7, column: 5, character: EMPTY_CHAR },
      { row: 7, column: 6, character: EMPTY_CHAR },
      { row: 7, column: 7, character: EMPTY_CHAR },
      { row: 7, column: 8, character: EMPTY_CHAR },
      { row: 7, column: 9, character: EMPTY_CHAR },
      { row: 7, column: 10, character: EMPTY_CHAR },
      { row: 7, column: 11, character: EMPTY_CHAR },
      { row: 7, column: 12, character: EMPTY_CHAR },
      { row: 7, column: 13, character: EMPTY_CHAR },
      { row: 7, column: 14, character: EMPTY_CHAR },
      { row: 7, column: 15, character: EMPTY_CHAR },
      { row: 7, column: 16, character: EMPTY_CHAR },
      { row: 7, column: 17, character: EMPTY_CHAR },
      { row: 7, column: 18, character: EMPTY_CHAR },
      { row: 7, column: 19, character: EMPTY_CHAR },
    ]);
  });
});
